require('bikesh.config')
require('bikesh.nvimTree') -- call nvimTree module at top to make sure nvim-tree works correctly
require('bikesh.keymap')
require('bikesh.plugins')
require('bikesh.telescope')
require('bikesh.lualine')
require('bikesh.lsp')
require('bikesh.nvim-treesitter')
require('bikesh.cmp')
require('bikesh.null-ls')
require('bikesh.comments')
require('bikesh.toggleterm')
